flaskblog/models.py
from flaskblog import db
from datetime import datetime


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False,
                           default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False,
                            default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

flaskblog/posts/models.py
from flaskblog import db
from flaskblog.users.models import User
from datetime import datetime


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False,
                            default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

flaskblog/users/models.py
from flaskblog import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False,
                           default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"

flaskblog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flaskblog.users.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password_conf = PasswordField('Confirm Password',
                                  validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Username already exists')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email already exists')


class LoginForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Sign In')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if not user:
            raise ValidationError('Username already exists')

flaskblog/__init__.py
from flask import Flask
import os
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ['FLASK_BLOG_SECRET']
db = SQLAlchemy(app)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = 'users.login_user'
login_manager.login_message_category = 'info'

from flaskblog.users.routes import users_blueprint
from flaskblog.posts.routes import posts_blueprint

app.config['SQLALCHEMY_DATABASE_URI'] = os.environ['FLASK_BLOG_DB_URL']
app.register_blueprint(users_blueprint)
app.register_blueprint(posts_blueprint)

from flaskblog import routes
from flaskblog.users import models
from flaskblog.posts import models

flaskblog/posts/routes.py
from flask import Blueprint

posts_blueprint = Blueprint('posts', __name__, url_prefix='/post')

from flaskblog.posts.models import Post


@posts_blueprint.route('/details')
def detailed_posts():
    return 'Detailed Posts'

flaskblog/routes.py
from flask import render_template

from flaskblog import app

posts = [
    {
        'author': 'Corey Schafer',
        'title': 'Blog Post 1',
        'content': 'First post content',
        'date_posted': 'April 20, 2018'
    },
    {
        'author': 'Jane Doe',
        'title': 'Blog Post 2',
        'content': 'Second post content',
        'date_posted': 'April 21, 2018'
    }
]


@app.route('/')
@app.route('/home')
def index():
    return render_template('home.html', posts=posts)


@app.route('/about')
def about():
    return render_template('about.html', title="About")

flaskblog/users/__init__.py
# from flaskblog.users import routes

flaskblog/users/routes.py
from flask import render_template, flash, redirect, url_for, Blueprint, request
from flaskblog.users.forms import RegistrationForm, LoginForm
from flask_login import login_user as user_login, current_user, logout_user as user_logout, login_required

users_blueprint = Blueprint('users', __name__, url_prefix='/user')
from flaskblog.users.models import User
from flaskblog import db, bcrypt


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        new_user = User(username=form.username.data,
                        password=hashed_password, email=form.email.data)
        db.session.add(new_user)
        db.session.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login_user'))
    return render_template('register.html', title='Register', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            user_login(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('index'))
        else:
            flash(f'Login Unsuccessful', 'danger')

    return render_template('login.html', title='Login', form=form)


@users_blueprint.route('/logout')
def logout_user():
    user_logout()
    return redirect(url_for('index'))


@users_blueprint.route('/account')
@login_required
def user_account():
    return render_template('account.html', title='Account')

flaskblog/templates/about.html
{% extends "base.html" %} {% block content %}
<h1>About Page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "base.html" %} {% block content %}
<h1>{{ current_user.username }}</h1>
{% endblock content %}

flaskblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{{ url_for('static',filename='css/main.css') }}">
    {% if title %}
    <title>{{ title }} - Flask Blog</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarToggle"
            aria-controls="navbarToggle"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/">Home</a>
              <a class="nav-item nav-link" href="/about">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated%}
                <a class="nav-item nav-link" href="{{ url_for('users.user_account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout_user') }}">Log Out</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login_user') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register_user') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category,message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock content %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

flaskblog/templates/home.html
{% extends "base.html" %} {% block content %} {% for post in posts %}
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="#">{{ post.author }}</a>
      <small class="text-muted">{{ post.date_posted }}</small>
    </div>
    <h2>
      <a class="article-title" href="#">{{ post.title }}</a>
    </h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %} {% endblock content %}

flaskblog/templates/login.html
{% extends "base.html" %} {% block content %}
<div class="content-section">
  <form method="POST">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">
        Join Today
      </legend>
      <div class="form-group">
        {{ form.username.label(class='form-control-label') }}
        {% if form.username.errors %}
        {{ form.username(class='form-control form-control-lg is-invalid') }}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.username(class='form-control form-control-lg') }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class='form-control-label') }}
        {% if form.password.errors %}
        {{ form.password(class='form-control form-control-lg is-invalid') }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.password(class='form-control form-control-lg') }}
        {% endif %}
      </div>
      <div class="form-check">
        {{ form.remember(class="form-check-input") }}
        {{ form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class='btn btn-outline-info') }}
    </div>
    <small class="text-muted">
      <a href="#">Forgot Password?</a>
    </small>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted"
    >Don't have an account?
    <a href="{{ url_for('users.register_user') }}">Sign Up</a></small
  >
</div>
{% endblock content %}

flaskblog/templates/register.html
{% extends "base.html" %} {% block content %}
<div class="content-section">
  <form method="POST">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">
        Join Today
      </legend>
      <div class="form-group">
        {{ form.username.label(class='form-control-label') }}
        {{ form.username(class='form-control form-control-lg') }}
      </div>
      <div class="form-group">
        {{ form.email.label(class='form-control-label') }}
        {{ form.email(class='form-control form-control-lg') }}
      </div>
      <div class="form-group">
        {{ form.password.label(class='form-control-label') }}
        {{ form.password(class='form-control form-control-lg') }}
      </div>
      <div class="form-group">
        {{ form.password_conf.label(class='form-control-label') }}
        {{ form.password_conf(class='form-control form-control-lg') }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class='btn btn-outline-info') }}
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted"
    >Already have an account?
    <a href="{{ url_for('users.login_user') }}">Sign In</a></small
  >
</div>
{% endblock content %}